<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMF9vWSA\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMF9vWSA/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMF9vWSA.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMF9vWSA\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMF9vWSA\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'MF9vWSA',
    'container.build_id' => '53e98218',
    'container.build_time' => 1516659846,
));
