<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUFVfM92\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUFVfM92/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUFVfM92.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUFVfM92\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerUFVfM92\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'UFVfM92',
    'container.build_id' => '62bfb23d',
    'container.build_time' => 1515538556,
));
